#### **Importing Essential Libraries**

In [93]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import tensorflow as tf
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow import keras
from tensorflow.keras import layers, models
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
import joblib

#### **Loading The Dataset**

In [29]:
df=pd.read_csv('diabetes_dataset.csv')
print(df.head())

   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   DiabetesPedigreeFunction  Age  Outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1

In [30]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

#### **Data Preprocessing**

##### **Replace the impossible 0 value by NAN**

In [32]:
cols_with_zero_missing = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI','Age']
df[cols_with_zero_missing] = df[cols_with_zero_missing].replace(0, np.nan)

#### **Impute missing values**

In [35]:
imputer = KNNImputer(n_neighbors=5)
df[cols_with_zero_missing] = imputer.fit_transform(df[cols_with_zero_missing])

In [36]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,169.0,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,58.6,26.6,0.351,31.0,0
2,8,183.0,64.0,23.4,174.6,23.3,0.672,32.0,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1

#### **Splitting into Features and Label**

In [37]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

#### **Splitting into Train,Test and validation set**

In [40]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, random_state=42, stratify=y_train)

In [42]:
print(f"X_train : {X_train.shape}")
print(f"y_train : {y_train.shape}")
print(f"X_val : {X_val.shape}")
print(f"y_val : {y_val.shape}")
print(f"X_test : {X_test.shape}")
print(f"y_test : {y_test.shape}")

X_train : (460, 8)
y_train : (460,)
X_val : (154, 8)
y_val : (154,)
X_test : (154, 8)
y_test : (154,)

#### **Baseline Model**

In [59]:
baseline_model=LogisticRegression(class_weight='balanced',max_iter=1000, random_state=42)

#### **Baseline Model Training**

In [60]:
baseline_model.fit(X_train,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

#### **Model Prediction**

In [61]:
y_val_pred=baseline_model.predict(X_val)
y_test_pred = baseline_model.predict(X_test)

In [62]:
print("Accuracy on Validation Dataset")
print("Accuracy:", accuracy_score(y_val,y_val_pred))
print("\nClassification Report:\n", classification_report(y_val,y_val_pred))

Accuracy on Validation Dataset
Accuracy: 0.7597402597402597

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.80      0.81       100
           1       0.65      0.69      0.67        54

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154

In [63]:
print("Accuracy on Test Dataset")
print("Accuracy:", accuracy_score(y_test, y_test_pred))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred))

Accuracy on Test Dataset
Accuracy: 0.7272727272727273

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.75      0.78       100
           1       0.60      0.69      0.64        54

    accuracy                           0.73       154
   macro avg       0.71      0.72      0.71       154
weighted avg       0.74      0.73      0.73       154

#### **Random Forest Model**

In [75]:
randomforest_model=RandomForestClassifier(class_weight='balanced',n_estimators=1000, random_state=42)

#### **Model Training**

In [76]:
randomforest_model.fit(X_train,y_train)

RandomForestClassifier(class_weight='balanced', n_estimators=1000,
                       random_state=42)

#### **Model Prediction**

In [77]:
y_val_pred_r=randomforest_model.predict(X_val)
y_test_pred_r = randomforest_model.predict(X_test)

In [78]:
print("Accuracy on Validation Dataset")
print("Accuracy:", accuracy_score(y_val,y_val_pred_r))
print("\nClassification Report:\n", classification_report(y_val,y_val_pred_r))

Accuracy on Validation Dataset
Accuracy: 0.7922077922077922

Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.88      0.85       100
           1       0.74      0.63      0.68        54

    accuracy                           0.79       154
   macro avg       0.78      0.75      0.76       154
weighted avg       0.79      0.79      0.79       154

In [79]:
print("Accuracy on Test Dataset")
print("Accuracy:", accuracy_score(y_test, y_test_pred_r))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred_r))

Accuracy on Test Dataset
Accuracy: 0.7467532467532467

Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.85      0.81       100
           1       0.67      0.56      0.61        54

    accuracy                           0.75       154
   macro avg       0.72      0.70      0.71       154
weighted avg       0.74      0.75      0.74       154

#### **XGBoost**

In [87]:
neg = sum(y_train == 0)
pos = sum(y_train == 1)
scale_pos_weight = neg / pos
print(scale_pos_weight)

1.875

In [88]:
xgb = XGBClassifier(n_estimators=300,max_depth=4,learning_rate=0.05,subsample=0.8,colsample_bytree=0.8,scale_pos_weight=1.875,random_state=42)

#### **XGBoost Model Training**

In [89]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=4,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, ...)

#### **XGBoost Model Prediction**

In [90]:
y_val_pred_x=xgb.predict(X_val)
y_test_pred_x = xgb.predict(X_test)

In [91]:
print("Accuracy on Validation Dataset")
print("Accuracy:", accuracy_score(y_val,y_val_pred_x))
print("\nClassification Report:\n", classification_report(y_val,y_val_pred_x))

Accuracy on Validation Dataset
Accuracy: 0.8051948051948052

Classification Report:
               precision    recall  f1-score   support

           0       0.87      0.82      0.85       100
           1       0.70      0.78      0.74        54

    accuracy                           0.81       154
   macro avg       0.79      0.80      0.79       154
weighted avg       0.81      0.81      0.81       154

In [92]:
print("Accuracy on Test Dataset")
print("Accuracy:", accuracy_score(y_test, y_test_pred_x))
print("\nClassification Report:\n", classification_report(y_test, y_test_pred_x))

Accuracy on Test Dataset
Accuracy: 0.7597402597402597

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.81      0.81       100
           1       0.65      0.67      0.66        54

    accuracy                           0.76       154
   macro avg       0.74      0.74      0.74       154
weighted avg       0.76      0.76      0.76       154

#### **Save Model**

In [95]:
joblib.dump(xgb, 'diabetes_model.pkl')
joblib.dump(imputer, "imputer.pkl")
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']